#docker-compose -f C:\Users\ivanov\source\repos\MatrixResponsibility\api.yml build; docker-compose -f C:\Users\ivanov\source\repos\MatrixResponsibility\api.yml up -d

services:
  api:
    build:
      context: .
      dockerfile: ./MatrixResponsibility/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=matrix_db;Username=user;Password=pass
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: matrix_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d matrix_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
        - db
    ports:
      - "8080:8080"

volumes:
  postgres_data: