#docker-compose -f C:\Users\ivanov\source\repos\MatrixResponsibility\testdb.yml up -d
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: matrix_db_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    links:
        - db
    ports:
      - "8080:8080"
  
volumes:
  postgres_data_test: